camera-kernel: Add missing event_data arguments
../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:3281:34: error: too few arguments to function call, expected 4, have 3
3280 |     __cam_isp_ctx_update_event_record(ctx_isp,
3281 |         CAM_ISP_CTX_EVENT_EPOCH, req);
     |         ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:81:13: note: '__cam_isp_ctx_update_event_record' declared here
  82 | static void __cam_isp_ctx_update_event_record(
  83 |     struct cam_isp_context *ctx_isp,
  84 |     enum cam_isp_ctx_event event,
  85 |     struct cam_ctx_request *req,
  86 |     void *event_data)
     |     ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:3603:43: error: too few arguments to function call, expected 4, have 3
3602 |     __cam_isp_ctx_update_event_record(ctx_isp,
3603 |         CAM_ISP_CTX_EVENT_EPOCH, active_req);
     |         ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:3673:34: error: too few arguments to function call, expected 4, have 3
3672 |     __cam_isp_ctx_update_event_record(ctx_isp,
3673 |         CAM_ISP_CTX_EVENT_EPOCH, req);
     |         ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:3737:31: error: too few arguments to function call, expected 4, have 3
3736 |     __cam_isp_ctx_update_event_record(ctx_isp,
3737 |         CAM_ISP_CTX_EVENT_RUP, req);
     |         ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:4000:34: error: too few arguments to function call, expected 4, have 3
3999 |     __cam_isp_ctx_update_event_record(ctx_isp,
4000 |         CAM_ISP_CTX_EVENT_EPOCH, req);
     |         ^

../../asahi-modules/qcom/opensource/camera-kernel/qcom/opensource/camera-kernel/drivers/cam_isp/cam_isp_context.c:7059:30: error: too few arguments to function call, expected 4, have 3
7058 |     __cam_isp_ctx_update_event_record(ctx_isp,
7059 |         CAM_ISP_CTX_EVENT_RUP, req);
     |         ^

Change-Id: I072444b9a774232a9d8e429040e77803246f5b4a
Signed-off-by: BladeRunner-A2C <creator4983@aospa.co>