camera-kernel: cam_csiphy: Remove implicit function declarations
../../asahi-modules/qcom/opensource/camera-kernel/drivers/cam_sensor_module/cam_csiphy/cam_csiphy_core.c:1794:9: error:
    call to undeclared function 'cam_csiphy_update_secure_info'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   1794 |         rc = cam_csiphy_update_secure_info(csiphy_dev, index);
        |         ^

../../asahi-modules/qcom/opensource/camera-kernel/drivers/cam_sensor_module/cam_csiphy/cam_csiphy_core.c:1794:9: note: did you mean 'cam_csiphy_parse_dt_info'?
../../asahi-modules/qcom/opensource/camera-kernel/drivers/cam_sensor_module/cam_csiphy/cam_csiphy_soc.h:55:5: note: 'cam_csiphy_parse_dt_info' declared here
    55 | int cam_csiphy_parse_dt_info(struct platform_device *pdev,
       |     ^

1 error generated.

 - Dropped in favor of: https://git.codelinaro.org/clo/la/platform/vendor/opensource/camera-kernel/-/commit/8bdffe141e39b555a8b29532ecf9d2e736cc7e14

Change-Id: Id57de17605611130ef51393bda1515ce9ae2dcbb
Signed-off-by: BladeRunner-A2C <creator4983@aospa.co>